BlogFronEnd/Controllers/BlogController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace BlogFronEnd.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index()
        {
            string url = ConfigurationManager.AppSettings["APIUrl"].ToString();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var response = client.GetAsync("Articles");
            response.Wait();

            var result = response.Result;
            if(result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsStringAsync();
                readTask.Wait();

                var articles = JsonConvert.DeserializeObject<List<Blog.DTO.ArticleDTO>>(readTask.Result);  
                return View(articles);
            }
            else
                return View();
        }

        [HttpGet]
        public ActionResult ReadArticle(int id)
        {
            string url = ConfigurationManager.AppSettings["APIUrl"].ToString();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var response = client.GetAsync("DisplayArticle?ID=" + id);
            response.Wait();

            var result = response.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsStringAsync();
                readTask.Wait();

                var article = JsonConvert.DeserializeObject<Blog.DTO.ArticleDTO>(readTask.Result);
                return View(article);
            }
            else
                return View();
        }
    }
}

BlogFronEnd/Controllers/ContactController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace BlogFronEnd.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Blog.DTO.ContactDTO contact)
        {
            postContact(contact);                        
            return Redirect("/Blog");
        }

        private void postContact(Blog.DTO.ContactDTO contact)
        {
            string Response = "";
            string url = ConfigurationManager.AppSettings["APIUrl"].ToString();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage HttpResponseMessage = null;
            JavaScriptSerializer jss = new JavaScriptSerializer();
            var myContent = jss.Serialize(contact);

            var httpContent = new StringContent(myContent, Encoding.UTF8, "application/json");            
            HttpResponseMessage = client.PostAsync("SaveContact", httpContent).Result;

            if (HttpResponseMessage.StatusCode == HttpStatusCode.OK)
            {
                Response = HttpResponseMessage.Content.ReadAsStringAsync().Result;
            }            
        }
    }
}

BlogFronEnd/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFronEnd.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BlogFronEnd/Views/Blog/Index.cshtml
@model List<Blog.DTO.ArticleDTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    Html.RenderPartial("~/Views/Shared/_Contact.cshtml", new Blog.DTO.ContactDTO());
    int y = 1;
    int x = 2;
    for (int i = 1; i <= Model.Count; i++)
    {
        if (i % 3 == 0 && i != 0)
        {
            if (x % 2 == 0)
            {
                <div class="row" style="text-align:left;">
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" style="float:right">
                        @Html.Partial("_Article", Model[i - 1])
                    </div>
                </div>
            }
            else
            {
                <div class="row" style="text-align:left;">
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" style="float:left">
                        @Html.Partial("_Article", Model[i - 1])
                    </div>
                </div>
            }
            x++;
        }
        else
        {
            <div class="row">
                <div class="col-lg-6 col-sm-6 col-xs-6 col-md-6">
                    @Html.Partial("_Article", Model[i - 1])
                </div>

                @if (i < Model.Count)
                {
                    <div class="col-lg-6 col-sm-6 col-xs-6 col-md-6">
                        @Html.Partial("_Article", Model[i])
                    </div>
                    i++;
                }
            </div>
        }
    }
}

BlogFronEnd/Views/Blog/ReadArticle.cshtml
@model Blog.DTO.ArticleDTO
@{
    ViewBag.Title = "ReadArticle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row articleHeader">
    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6">
        <img src="@Model.ImageURL" style="width:100%"/>
    </div>
    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6">
        <div class="row">
            <h2>@Model.Title</h2>
            <br />
            Date: @Model.Created.ToString("dd MMM yyyy")                        
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-1 col-sm-1 col-md-1 col-xs-1">
        &nbsp;
    </div>
    <div class="col-lg-10 col-sm-10 col-md-10 col-xs-10">
        @Model.Body
    </div>
    <div class="col-lg-1 col-sm-1 col-md-1 col-xs-1">
        &nbsp;
    </div>
</div>

BlogFronEnd/Views/Shared/_Article.cshtml
@model Blog.DTO.ArticleDTO
<div class="row articleContainer">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-4">
                <img src="@Model.ImageURL" width="100" />
            </div>
            <div class="col-lg-8">
                <p>
                    @Model.Description
                </p>
                @Html.ActionLink("Read more...", "ReadArticle", "Blog", new { id = Model.ID }, null);
            </div>
        </div>
    </div>
</div>

BlogFronEnd/Views/Shared/_ArticleSingle.cshtml
@model Blog.DTO.ArticleDTO
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-4">
                <img src="@Model.ImageURL" width="100" />
            </div>
            <div class="col-lg-8">
                <p>
                    @Model.Description
                </p>
                @Html.ActionLink("Read more...", "ReadArticle", "Blog", new { id = Model.ID }, null);
            </div>
        </div>
    </div>
</div>

BlogFronEnd/Views/Shared/_Contact.cshtml
@model Blog.DTO.ContactDTO

<div id="dialog-modal" style="overflow:hidden">
    @using (Ajax.BeginForm("Index", "Contact", new AjaxOptions { UpdateTargetId = "ID", HttpMethod = "POST", OnSuccess="onSuccess" }))
    {
        <div class="row" style="padding-left:40px; padding-top: 20px">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        @Html.LabelFor(m => m.Name)
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.TextBoxFor(m => m.Name, new { Style = "width:100%" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        @Html.LabelFor(m => m.EmailAddress)
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.TextBoxFor(m => m.EmailAddress, new { Style = "width:100%" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        @Html.LabelFor(m => m.ContactNumber)
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.TextBoxFor(m => m.ContactNumber, new { Style = "width:100%" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                        @Html.LabelFor(m => m.Message)
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        @Html.TextAreaFor(m => m.Message, new { Style = "width:100%" })
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="text-align:center">
                <input type="submit" value="Store" style="background-color:#272727; color:white;" />
            </div>
        </div>
    }
</div>

BlogFronEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Blog Test", "Index", "Blog", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Blog", "Index", "Blog")</li>
                    <li>&nbsp;</li>
                    <li><a id="contact" href="#">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="border-width:1px; border-color:black;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(function () {
            $('#dialog-modal').dialog({
                autoOpen: false,
                width: 400,
                height: 500,
                show: {
                    effect: 'blind',
                    duration: 1000
                },
                hide:
                {
                    effect: 'explode',
                    duration: 1000
                }
            });
        });

        $('#contact').click(function () {            
            $('#dialog-modal').dialog("open");
        });
    </script>
</body>
</html>